post http://localhost:3001/api/notes
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZsYWQxMjMiLCJpZCI6IjVkNDRhYjcyOTdjMmY4NTIxYzJlYzE0MSIsImlhdCI6MTU2NTk4NjA2MH0.w8pyjuJ-6e2WvVa0NWLOeFk0OuuKDy7bT_MiFS03CYI

{
  "content": "VS Code REST client should have auth (one MORE time to test)",
  "important": true
}